import React from "react";
import * as Icon from "react-feather";
const navigationConfig = [
  {
    id: "home",
    title: "Home",
    type: "item",
    icon: <Icon.Home size={20} />,
    navLink: "/",
  },
  {
    type: "groupHeader",
    groupTitle: "DATA & MAPS",
  },
  {
    id: "analytics",
    title: "Analytics",
    type: "item",
    icon: <Icon.BarChart2 size={20} />,
    navLink: "/cards/analytics",
  },
  {
    id: "dataTable",
    title: "DataTables",
    type: "item",
    icon: <Icon.Server size={20} />,
    navLink: "/tables/data-tables",
  },
  {
    id: "leafletMaps",
    title: "Leaflet Maps",
    icon: <Icon.Map size={20} />,
    type: "item",
    navLink: "/maps/leaflet",
  },
  {
    id: "statistics",
    title: "Statistics",
    type: "item",
    icon: <Icon.BarChart size={20} />,
    navLink: "/cards/statistics",
  },
  {
    type: "groupHeader",
    groupTitle: "E-COMMERCE PAGES",
  },
  {
    id: "shop",
    title: "Shop",
    type: "item",
    icon: <Icon.ShoppingCart size={20} />,
    navLink: "/ecommerce/shop",
  },
  {
    id: "detail",
    title: "Item Details",
    type: "item",
    icon: <Icon.AlignCenter size={20} />,
    navLink: "/ecommerce/product-detail",
  },
  {
    id: "wishList",
    title: "Wish List",
    type: "item",
    icon: <Icon.Heart size={20} />,
    navLink: "/ecommerce/wishlist",
  },
  {
    id: "checkout",
    title: "Checkout",
    type: "item",
    icon: <Icon.DollarSign size={20} />,
    navLink: "/ecommerce/checkout",
  },
  {
    type: "groupHeader",
    groupTitle: "WEB APPS",
  },
  {
    id: "todo",
    title: "Tasks",
    type: "item",
    icon: <Icon.List size={20} />,
    navLink: "/todo/:filter",
    filterBase: "/todo/all",
  },
  {
    id: "email",
    title: "Email",
    type: "item",
    icon: <Icon.Mail size={20} />,
    navLink: "/email/:filter",
    filterBase: "/email/inbox",
  },
  {
    id: "chat",
    title: "Messenger",
    type: "item",
    icon: <Icon.MessageSquare size={20} />,
    navLink: "/chat",
  },
  {
    id: "calendar",
    title: "Calendar",
    type: "item",
    icon: <Icon.Calendar size={20} />,
    navLink: "/calendar",
  },
  {
    type: "groupHeader",
    groupTitle: "AUTHENTICATION PAGES",
  },
  {
    id: "login",
    title: "Login",
    type: "item",
    icon: <Icon.LogIn size={20} />,
    navLink: "/pages/login",
  },
  {
    id: "register",
    title: "Register",
    type: "item",
    icon: <Icon.Edit size={20} />,
    navLink: "/pages/register",
  },
  {
    id: "forgotPassword",
    title: "Forgot Password",
    type: "item",
    icon: <Icon.Lock size={20} />,
    navLink: "/pages/forgot-password",
  },
  {
    id: "resetPassword",
    title: "Reset Password",
    type: "item",
    icon: <Icon.Repeat size={20} />,
    navLink: "/pages/reset-password",
  },
  {
    type: "groupHeader",
    groupTitle: "EXTRA PAGES",
  },
  {
    id: "comingSoon",
    title: "Coming Soon",
    type: "item",
    icon: <Icon.Clock size={20} />,
    navLink: "/misc/coming-soon",
  },
  {
    id: "notAuthorized",
    title: "Not Authorized",
    type: "item",
    icon: <Icon.AlertTriangle size={20} />,
    navLink: "/misc/not-authorized",
  },
  {
    id: "maintenance",
    title: "Maintenance",
    type: "item",
    icon: <Icon.AlertOctagon size={20} />,
    navLink: "/misc/maintenance",
  },
  {
    id: "404",
    title: "404",
    type: "item",

    icon: <Icon.AlertCircle size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/misc/error/404",
  },
  {
    id: "500",
    title: "500",
    type: "item",
    icon: <Icon.Terminal size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/misc/error/500",
  },
  {
    type: "groupHeader",
    groupTitle: "FORM LAYOUTS & ELEMENTS",
  },
  {
    id: "formLayouts",
    title: "Form Layouts",
    type: "item",
    icon: <Icon.Box size={20} />,
    navLink: "/forms/layout/form-layout",
  },
  {
    id: "select",
    title: "Select",
    type: "item",
    icon: <Icon.Pocket size={20} />,
    navLink: "/forms/elements/select",
  },
  {
    id: "switch",
    title: "Switch",
    type: "item",
    icon: <Icon.ToggleRight size={20} />,
    navLink: "/forms/elements/switch",
  },
  {
    id: "checkbox",
    title: "Checkbox",
    type: "item",
    icon: <Icon.CheckSquare size={20} />,
    navLink: "/forms/elements/checkbox",
  },
  {
    id: "radio",
    title: "Radio",
    type: "item",
    icon: <Icon.Disc size={20} />,
    navLink: "/forms/elements/radio",
  },
  {
    id: "input",
    title: "Input",
    type: "item",
    icon: <Icon.Edit2 size={20} />,
    navLink: "/forms/elements/input",
  },
  {
    id: "inputGroup",
    title: "Input Group",
    type: "item",
    icon: <Icon.Edit size={20} />,
    navLink: "/forms/elements/input-group",
  },
  {
    id: "numberInput",
    title: "Number Input",
    type: "item",
    icon: <Icon.PlusSquare size={20} />,
    navLink: "/forms/elements/number-input",
  },
  {
    id: "textarea",
    title: "Textarea",
    type: "item",
    icon: <Icon.FileText size={20} />,
    navLink: "/forms/elements/textarea",
  },
  {
    id: "date_&_timePicker",
    title: "Date & Time Picker",
    type: "item",
    icon: <Icon.Calendar size={20} />,
    navLink: "/forms/elements/pickers",
  },
  {
    id: "inputMask",
    title: "Input Mask",
    type: "item",
    icon: <Icon.Edit3 size={20} />,
    navLink: "/forms/elements/input-mask",
  },
];

export default navigationConfig;
